### ISSUE TITLE
Add the Binance Dexathon

### ISSUE THREAD

**Issue by mewc** [sdesalas/melbourne-hackathons#10]
![img_20180417_092718](https://user-images.githubusercontent.com/15105417/38840298-3e66d46a-4222-11e8-8eb7-2994be1cf195.jpg)
![img_20180417_092713](https://user-images.githubusercontent.com/15105417/38840297-3e26c1ae-4222-11e8-82d1-0e0a08c5f973.jpg)

https://www.eventbrite.com.au/e/canya-bountysource-typehyman-binance-dexathon-melbourne-tickets-44867266201?aff=efbneb

**Comment by sdesalas** [comment]
👍  thanks!
